// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlptVOELSHs2tmmEUtwpH2EVUPa-Rr1Ys',
    appId: '1:857940572180:web:db2a4887574c0c3bf84f01',
    messagingSenderId: '857940572180',
    projectId: 'csci-567-s26',
    authDomain: 'csci-567-s26.firebaseapp.com',
    storageBucket: 'csci-567-s26.firebasestorage.app',
    measurementId: 'G-GNMKSMX5XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVP0FCNc7rn6gLd9jG3yv8o-YQCm2v3Cs',
    appId: '1:857940572180:android:65b4c71b8e8dcfb3f84f01',
    messagingSenderId: '857940572180',
    projectId: 'csci-567-s26',
    storageBucket: 'csci-567-s26.firebasestorage.app',
  );

}